android/platform-samples

samples/location/src/main/java/com/example/platform/location/permission/LocationPermissionsScreen.kt, samples/privacy/permissions/src/main/java/com/example/platform/privacy/permissions/ComposePermissions.kt, samples/privacy/permissions/src/main/java/com/example/platform/privacy/permissions/MultiplePermissions.kt, samples/privacy/permissions/src/main/java/com/example/platform/privacy/permissions/SinglePermission.kt, samples/user-interface/constraintlayout/src/main/java/com/example/platform/ui/constraintlayout/ConstraintLayout.kt, samples/user-interface/constraintlayout/src/main/java/com/example/platform/ui/constraintlayout/MotionLayout.kt, samples/user-interface/haptics/src/main/java/com/example/platform/ui/haptics/Haptics.kt, samples/user-interface/text/src/main/java/com/example/platform/ui/text/ConversionSuggestions.kt, samples/user-interface/text/src/main/java/com/example/platform/ui/text/Hyphenation.kt, samples/user-interface/text/src/main/java/com/example/platform/ui/text/LineBreak.kt, samples/user-interface/text/src/main/java/com/example/platform/ui/text/Linkify.kt, samples/user-interface/text/src/main/java/com/example/platform/ui/text/TextSpan.kt
This creates a new filter label to help navigate.
=> Add common-tags to samples

samples/user-interface/constraintlayout/README.md, samples/user-interface/constraintlayout/src/main/java/com/example/platform/ui/constraintlayout/MotionLayout.kt
Change-Id: Ib50d5737c491fc079b7d6c7435e905e6dd55a907
=> ConstraintLayout: Update readme

samples/user-interface/window-insets/src/main/java/com/example/platform/ui/insets/ImmersiveMode.kt
Change-Id: I58f52633e4dbe00954d70f54e86f2fd959396baa
=> ImmersiveMode: Use BEHAVIOR_DEFAULT from AndroidX

gradle.properties
Build started to randomly fail with OOM.
=> Increase Metaspace size

build-logic/src/main/kotlin/com.example.platform.plugin/SamplePlugin.kt, gradle/libs.versions.toml, samples/location/build.gradle.kts
Updating to casa v.0.4.2 should fix the search bar issue #31 
Fix: #31 
Change-Id: I82d94bf6bea13c87e62a694ffc6c1fa4fa92a957
=> Update and clean dependencies

app/build.gradle.kts, build-logic/src/main/kotlin/com.example.platform.plugin/SamplePlugin.kt, samples/user-interface/constraintlayout/src/main/java/com/example/platform/ui/constraintlayout/view/BoundsImageView.kt
With SDK 34 in stable milestone we can move the target to 34
=> Update targetSDK to 34

samples/user-interface/windowmanager/src/main/AndroidManifest.xml, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/demos/WindowDemosActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/ExampleWindowInitializer.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitAttributesToggleActivityBase.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitAttributesToggleMainActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitAttributesTogglePlaceholderActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitAttributesTogglePrimaryActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitAttributesToggleSecondaryActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitDeviceStateActivityA.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitDeviceStateActivityB.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitDeviceStateActivityBase.kt, samples/user-interface/windowmanager/src/main/res/layout/activity_split_attributes_toggle_primary_activity.xml, samples/user-interface/windowmanager/src/main/res/layout/activity_split_attributes_toggle_secondary_activity.xml, samples/user-interface/windowmanager/src/main/res/layout/activity_split_device_state_layout.xml, samples/user-interface/windowmanager/src/main/res/values/strings.xml
- SplitDeviceStateActivity shows how to react to device state changes
- SplitAttributesToggleActivity shows how to use different parameters
=> Added demoes of different Split Layouts

samples/README.md, samples/connectivity/bluetooth/ble/src/main/AndroidManifest.xml, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/BluetoothSampleBox.kt, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/ConnectGATTSample.kt, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/FindBLEDevicesSample.kt, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/FindDevicesSample.kt, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/GATTServerSample.kt
Migrate legacy BLE samples and create a new simple one with a server and a client that communicates.
The samples share code between them but the sample itself contains the needed parts for each CUJ.
Client:
Server:
=> BLE GATT sample

samples/user-interface/picture-in-picture/src/main/java/com/example/android/pip/PiPSampleActivity.kt
Change-Id: I5ca22ab8e7bedca531a91df35c839c0814f04eee
=> PictureInPicture: Fix use of BroadcastReceiver

samples/README.md, samples/connectivity/bluetooth/ble/src/main/AndroidManifest.xml, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/BLEScanIntentSample.kt, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/ConnectGATTSample.kt, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/FindBLEDevicesSample.kt, samples/connectivity/bluetooth/ble/src/main/java/com/example/platform/connectivity/bluetooth/ble/GATTServerSample.kt
The new sample showcases how to use the startScan method with a pending intent
=> Sample BLE startScan with Pending Intent

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, README.md, tools/pre-push
Fixed a small typo: gradle/init.gradle.kts -> gradle/spotless-init.gradle.kts
resolves #75
=> Fix typo regarding spotless-init.gradle.kts

app/src/main/AndroidManifest.xml
Add back-to-home predictive back animation: https://photos.app.goo.gl/DGwSegURcagk1Vw27
=> Add back-to-home predictive back animation

samples/location/src/main/java/com/example/platform/location/bglocationaccess/BgLocationAccessScreen.kt
=> Update BgLocationAccessScreen interval

build-logic/src/main/kotlin/com.example.platform.plugin/SamplePlugin.kt, gradle/libs.versions.toml, samples/README.md, samples/connectivity/callnotification/src/main/java/com/example/platform/connectivity/callnotification/CallNotificationSample.kt
Use CASA theme for samples that setContent
=> Update to casa v0.4.4

samples/user-interface/predictiveback/README.md, samples/user-interface/predictiveback/src/main/AndroidManifest.xml, samples/user-interface/predictiveback/src/main/java/com/example/platform/ui/predictiveback/PBAnimation.kt, samples/user-interface/predictiveback/src/main/java/com/example/platform/ui/predictiveback/PBCustomCrossActivityAnimation.kt, samples/user-interface/predictiveback/src/main/java/com/example/platform/ui/predictiveback/PBListFragment.kt, samples/user-interface/predictiveback/src/main/res/layout/activity_custom_cross_animation.xml, samples/user-interface/predictiveback/src/main/res/layout/fragment_animation_list.xml, samples/user-interface/predictiveback/src/main/res/navigation/nav_graph.xml, samples/user-interface/predictiveback/src/main/res/values/strings.xml
video: https://photos.google.com/photo/AF1QipMyzjxkXpPBROjEpw4x-1DhYfaiywttXajPyx3m
=> Predictive back custom cross activity

gradle/libs.versions.toml, samples/user-interface/windowmanager/build.gradle.kts, samples/user-interface/windowmanager/src/main/AndroidManifest.xml, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/RearDisplayModeActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/demos/WindowDemosActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/ExampleWindowInitializer.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitAttributesToggleMainActivity.kt, samples/user-interface/windowmanager/src/main/java/com/example/platform/ui/windowmanager/embedding/SplitDeviceStateActivityBase.kt, samples/user-interface/windowmanager/src/main/res/layout/activity_rear_display_mode.xml, samples/user-interface/windowmanager/src/main/res/values/strings.xml
=>  updated windowmanager to 1.2-beta3

app/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
Upgrade casa along with Compose, Kotlin and other dependencies.
Hilt runs on KSP now.
Change-Id: Icf2ad77ea1d0709b7a083ca7a032036b1cd05d11
=> Upgrade to casa v0.5.0

.idea/kotlinc.xml, build-logic/src/main/kotlin/com.example.platform.plugin/SamplePlugin.kt
Change-Id: Ie92589e608adddee9894a624ac37746a2550409f
=> Fix the script for generating a new sample

samples/connectivity/bluetooth/ble/README.md
Fixing issue #138 where link to GattServerSample is broken.
=> Fix link in ReadMe

samples/user-interface/appwidgets/src/main/java/com/example/platform/ui/appwidgets/AppWidgets.kt, samples/user-interface/appwidgets/src/main/java/com/example/platform/ui/appwidgets/glance/GlanceKtx.kt
Changes:
* Scope custom modifier as `GlanceModifer` extension
* Minor refactor to help with readability
=> Refactor appWidgetBackgroundModifier as GlanceModifier extension.

samples/user-interface/predictiveback/README.md, samples/user-interface/predictiveback/src/main/java/com/example/platform/ui/predictiveback/PBAnimation.kt, samples/user-interface/predictiveback/src/main/java/com/example/platform/ui/predictiveback/PBListFragment.kt, samples/user-interface/predictiveback/src/main/java/com/example/platform/ui/predictiveback/PBSharedElementTransitionFragment.kt, samples/user-interface/predictiveback/src/main/res/layout/fragment_animation_list.xml, samples/user-interface/predictiveback/src/main/res/layout/fragment_shared_element_transition.xml, samples/user-interface/predictiveback/src/main/res/navigation/nav_graph.xml, samples/user-interface/predictiveback/src/main/res/values/strings.xml
Add a Predictive Back cross fragment shared element transition sample.
Video: https://photos.app.goo.gl/Et8F17wSZgmk5aNK9
=> Predictive Back Cross Fragment Shared Element Transition Sample

.gitignore, .idea/kotlinc.xml, gradle/libs.versions.toml, samples/README.md, samples/user-interface/appwidgets/build.gradle.kts, samples/user-interface/constraintlayout/build.gradle.kts, samples/user-interface/draganddrop/build.gradle.kts, samples/user-interface/predictiveback/build.gradle.kts, samples/user-interface/text/build.gradle.kts, samples/user-interface/window-insets/build.gradle.kts, samples/user-interface/windowmanager/build.gradle.kts, settings.gradle.kts
Also upgrade other dependencies.
Change-Id: I98680e5ebbe31b1a3b2a84c333db63995f1ef56c
=> Upgrade casa to v0.5.1

samples/user-interface/predictiveback/src/main/java/com/example/platform/ui/predictiveback/PBProgressAPI.kt
add STANDARD_DECLERATE interpolator to the progressAPI
=> add STANDARD_DECLERATE interpolator to the progressAPI

samples/user-interface/picture-in-picture/src/main/AndroidManifest.xml
add launchMode to singleTask as per best practice
=> Update AndroidManifest.xml PiP activities

gradle/libs.versions.toml, samples/README.md, samples/user-interface/draganddrop/build.gradle.kts, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropMultiWindow.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropRichContentReceiverFragment.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropUsingCompose.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropWithHelper.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/RichContentReceiverAdapter.kt, samples/user-interface/draganddrop/src/main/res/layout/fragment_dnd_multiwindow.xml, samples/user-interface/draganddrop/src/main/res/layout/fragment_dnd_richcontent.xml, samples/user-interface/draganddrop/src/main/res/layout/fragment_drag_and_drop_with_helper.xml, samples/user-interface/draganddrop/src/main/res/layout/grid_item.xml, samples/user-interface/draganddrop/src/main/res/values/strings.xml
Updated the Drag and Drop sample to include separate implementation for
1. Drag and Drop using Views
2. Drag and Drop using DragAndDropHelper
3. Drag and Drop in Multi-Window Mode across apps
4. Drag and Drop using RichContentReciever
5. Drag and Drop in Compose
=> Drag and Drop samples update

samples/README.md, samples/user-interface/draganddrop/README.md, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDrop.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropFileProvider.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropMultiWindow.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropRichContentReceiverFragment.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropWithHelper.kt, samples/user-interface/draganddrop/src/main/java/com/example/platform/ui/draganddrop/DragAndDropWithViews.kt, samples/user-interface/draganddrop/src/main/res/layout/fragment_dnd_richcontent.xml, samples/user-interface/draganddrop/src/main/res/layout/fragment_drag_and_drop_with_views.xml, samples/user-interface/draganddrop/src/main/res/values/strings.xml
Change-Id: I78a68213910b38c3818ff8cf5519a37da8ebd6eb
=> Drag and Drop using views
